# Generated by Django 4.2.1 on 2023-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='title',
            name='dir_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='title',
            name='rus_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='title',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
