# Generated by Django 4.2.1 on 2023-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0004_title_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='count_bookmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='count_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='issue_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
