# Generated by Django 4.2.1 on 2023-05-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0005_title_count_bookmarks_title_count_chapters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
