# Generated by Django 4.2.1 on 2023-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0008_genres_title_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='count_rating',
            field=models.IntegerField(default=0),
        ),
    ]
