# Generated by Django 4.2.1 on 2023-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0009_title_count_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(default='', max_length=100)),
                ('tome', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='chapters',
            field=models.ManyToManyField(to='remanga.chapters'),
        ),
    ]
