# Generated by Django 4.2.1 on 2023-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0010_chapters_title_chapters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'ordering': ['-chapter']},
        ),
        migrations.AlterField(
            model_name='chapters',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
    ]
